# Application name
spring.application.name=spring-boot-mongo

# EMBEDDED SERVER CONFIGURATION
# Server HTTP port.
server.port=8080

# LOGGING
logging.level.root=WARN
logging.level.org.springframework.web=DEBUG
logging.level.com.spring.boot.redis=DEBUG
logging.pattern.console=${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %4line %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

# MONGODB (MongoProperties)
# Authentication database name.
# spring.data.mongodb.authentication-database=
# Database name.
spring.data.mongodb.database=
# Fully qualified name of the FieldNamingStrategy to use.
# spring.data.mongodb.field-naming-strategy=
# GridFS database name.
# spring.data.mongodb.grid-fs-database=
# Mongo server host. Cannot be set with URI.
spring.data.mongodb.host=localhost
# Login password of the mongo server. Cannot be set with URI.
spring.data.mongodb.password=
# Mongo server port. Cannot be set with URI.
spring.data.mongodb.port=27017
# Type of Mongo repositories to enable.
# spring.data.mongodb.repositories.type=auto
# Mongo database URI. Cannot be set with host, port and credentials.
# spring.data.mongodb.uri=mongodb://localhost/test
# Login user of the mongo server. Cannot be set with URI.
spring.data.mongodb.username=

