spring.application.name=spring-boot-mongo
server.port=8080

# LOGGING
logging.level.com.spring.boot.mongo=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
logging.pattern.console=${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %4line %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

#spring.data.mongodb.database=artanis
#spring.data.mongodb.host=192.168.31.135
#spring.data.mongodb.port=27017
#spring.data.mongodb.repositories.type=auto
#spring.data.mongodb.authentication-database=admin
#spring.data.mongodb.username=root
#spring.data.mongodb.password=PassW0rd321

# connect to database artanis, if not exit, create it
# must connect to master
spring.data.mongodb.uri=mongodb://192.168.17.139:30003/artanis

# 以下方式不行
#spring.data.mongodb.uri=mongodb://192.168.31.135:27017,192.168.31.139:27017,192.168.31.140:27017/artanis?replicaSet=rs0&connectTimeoutMS=300000
#spring.data.mongodb.uri=mongodb://192.168.31.139:30001,192.168.31.139:30002,192.168.31.139:30001/artanis?replicaSet=rs&connectTimeoutMS=300000
