server.port=8080
spring.application.name=spring-boot-mongo

# LOGGING
logging.level.com.spring.boot.mongo=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
logging.pattern.console=${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %4line %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

spring.data.mongodb.database=artanis
spring.data.mongodb.host=192.168.31.138
spring.data.mongodb.port=27017
spring.data.mongodb.repositories.type=auto
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=root
spring.data.mongodb.password=.P@ssW0rd,321
