# Application name
spring.application.name=spring-boot-mybatisplus-hikaricp


# EMBEDDED SERVER CONFIGURATION
# Server HTTP port.
server.port=8080


# LOGGING
########################################################################################################################
logging.level.root=WARN
logging.level.org.springframework.web=DEBUG
logging.level.com.spring.boot.mybatis=DEBUG
logging.pattern.console=${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %4line %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}


# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
########################################################################################################################
# Hikari will use the above plus the following to setup connection pooling
# Fully qualified name of the JDBC driver. Auto-detected based on the URL by default.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JDBC URL of the database.
# useSSL=false 关闭SSL验证
# serverTimezone=UTC 设置时区
spring.datasource.url=jdbc:mysql://localhost:3306/artanis?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=utf8
# Login username of the database.
spring.datasource.username=root
# Login password of the database.
spring.datasource.password=.Gaohang,321


# Hikari specific settings
########################################################################################################################
# Fully qualified name of the connection pool implementation to use. By default, it is auto-detected from the classpath.
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
#======================================================================================================================#
# Frequently used 常用项
# This property controls the default auto-commit behavior of connections returned from the pool. It is a boolean value. Default: true
spring.datasource.hikari.autoCommit=true

# This property controls the maximum number of milliseconds that a client (that's you) will wait for a connection from the pool.
# If this time is exceeded without a connection becoming available, a SQLException will be thrown.
# Lowest acceptable connection timeout is 250 ms. Default: 30000 (30 seconds)
spring.datasource.hikari.connectionTimeout=30000

# This property controls the maximum amount of time that a connection is allowed to sit idle in the pool.
# This setting only applies when minimumIdle is defined to be less than maximumPoolSize.
# Idle connections will not be retired once the pool reaches minimumIdle connections.
# Whether a connection is retired as idle or not is subject to a maximum variation of +30 seconds, and average variation of +15 seconds.
# A connection will never be retired as idle before this timeout. A value of 0 means that idle connections are never removed from the pool.
# The minimum allowed value is 10000ms (10 seconds). Default: 600000 (10 minutes)
spring.datasource.hikari.idleTimeout=600000

# This property controls the maximum lifetime of a connection in the pool. An in-use connection will never be retired, only when it is closed will it then be removed.
# On a connection-by-connection basis, minor negative attenuation is applied to avoid mass-extinction in the pool.
# We strongly recommend setting this value, and it should be several seconds shorter than any database or infrastructure imposed connection time limit.
# A value of 0 indicates no maximum lifetime (infinite lifetime), subject of course to the idleTimeout setting. Default: 1800000 (30 minutes)
spring.datasource.hikari.maxLifetime=1800000

# If your driver supports JDBC4 we strongly recommend not setting this property. This is for "legacy" drivers that do not support the JDBC4 Connection.isValid() API.
# This is the query that will be executed just before a connection is given to you from the pool to validate that the connection to the database is still alive. Again,
# try running the pool without this property, HikariCP will log an error if your driver is not JDBC4 compliant to let you know. Default: none
spring.datasource.hikari.connectionTestQuery=SELECT 1

# This property controls the minimum number of idle connections that HikariCP tries to maintain in the pool.
# If the idle connections dip below this value and total connections in the pool are less than maximumPoolSize,
# HikariCP will make a best effort to add additional connections quickly and efficiently.
# However, for maximum performance and responsiveness to spike demands, we recommend not setting this value and instead allowing HikariCP to act as a fixed size connection pool.
# Default: same as maximumPoolSize
spring.datasource.hikari.minimumIdle=10

# This property controls the maximum size that the pool is allowed to reach, including both idle and in-use connections.
# Basically this value will determine the maximum number of actual connections to the database backend.
# A reasonable value for this is best determined by your execution environment.
# When the pool reaches this size, and no idle connections are available, calls to getConnection() will block for up to connectionTimeout milliseconds before timing out.
# Please read about pool sizing. Default: 10
spring.datasource.hikari.maximumPoolSize=10

# This property is only available via programmatic configuration or IoC container.
# This property allows you to specify an instance of a Codahale/Dropwizard MetricRegistry to be used by the pool to record various metrics.
# See the Metrics wiki page for details. Default: none
#    spring.datasource.hikari.metricRegistry=

# This property is only available via programmatic configuration or IoC container.
# This property allows you to specify an instance of a Codahale/Dropwizard HealthCheckRegistry to be used by the pool to report current health information.
# See the Health Checks wiki page for details. Default: none
#    spring.datasource.hikari.healthCheckRegistry=

# This property represents a user-defined name for the connection pool and appears mainly in logging and JMX management consoles to identify pools and pool configurations.
# Default: auto-generated
spring.datasource.hikari.poolName=DatebookHikariCP
#======================================================================================================================#
# Infrequently used 非常用项
# This property controls whether the pool will "fail fast" if the pool cannot be seeded with an initial connection successfully.
# Any positive number is taken to be the number of milliseconds to attempt to acquire an initial connection; the application thread will be blocked during this period.
# If a connection cannot be acquired before this timeout occurs, an exception will be thrown. This timeout is applied after the connectionTimeout period.
# If the value is zero (0), HikariCP will attempt to obtain and validate a connection.
# If a connection is obtained, but fails validation, an exception will be thrown and the pool not started.
# However, if a connection cannot be obtained, the pool will start, but later efforts to obtain a connection may fail.
# A value less than zero will bypass any initial connection attempt, and the pool will start immediately while trying to obtain connections in the background.
# Consequently, later efforts to obtain a connection may fail. Default: 1
#    spring.datasource.hikari.initializationFailTimeout=1

# This property determines whether HikariCP isolates internal pool queries, such as the connection alive test, in their own transaction.
# Since these are typically read-only queries, it is rarely necessary to encapsulate them in their own transaction.
# This property only applies if autoCommit is disabled. Default: false
#    spring.datasource.hikari.isolateInternalQueries=false

# This property controls whether the pool can be suspended and resumed through JMX. This is useful for certain failover automation scenarios.
# When the pool is suspended, calls to getConnection() will not timeout and will be held until the pool is resumed. Default: false
#    spring.datasource.hikari.allowPoolSuspension=false

# This property controls whether Connections obtained from the pool are in read-only mode by default.
# Note some databases do not support the concept of read-only mode, while others provide query optimizations when the Connection is set to read-only.
# Whether you need this property or not will depend largely on your application and database. Default: false
#    spring.datasource.hikari.readOnly=false

# This property controls whether or not JMX Management Beans ("MBeans") are registered or not. Default: false
#    spring.datasource.hikari.registerMbeans=false

# This property sets the default catalog for databases that support the concept of catalogs.
# If this property is not specified, the default catalog defined by the JDBC driver is used. Default: driver default
#    spring.datasource.hikari.catalog=

# This property sets a SQL statement that will be executed after every new connection creation before adding it to the pool.
# If this SQL is not valid or throws an exception, it will be treated as a connection failure and the standard retry logic will be followed. Default: none
#    spring.datasource.hikari.connectionInitSql=

# HikariCP will attempt to resolve a driver through the DriverManager based solely on the jdbcUrl, but for some older drivers the driverClassName must also be specified.
# Omit this property unless you get an obvious error message indicating that the driver was not found. Default: none
#    spring.datasource.hikari.driverClassName=

# This property controls the default transaction isolation level of connections returned from the pool.
# If this property is not specified, the default transaction isolation level defined by the JDBC driver is used.
# Only use this property if you have specific isolation requirements that are common for all queries.
# The value of this property is the constant name from the Connection class such as TRANSACTION_READ_COMMITTED, TRANSACTION_REPEATABLE_READ, etc. Default: driver default
#    spring.datasource.hikari.transactionIsolation=

# This property controls the maximum amount of time that a connection will be tested for aliveness. This value must be less than the connectionTimeout.
# Lowest acceptable validation timeout is 250 ms. Default: 5000
#    spring.datasource.hikari.validationTimeout=5000

# This property controls the amount of time that a connection can be out of the pool before a message is logged indicating a possible connection leak.
# A value of 0 means leak detection is disabled. Lowest acceptable value for enabling leak detection is 2000 (2 seconds). Default: 0
#    spring.datasource.hikari.leakDetectionThreshold=0

# This property is only available via programmatic configuration or IoC container.
# This property allows you to directly set the instance of the DataSource to be wrapped by the pool, rather than having HikariCP construct it via reflection.
# This can be useful in some dependency injection frameworks. When this property is specified,
# the dataSourceClassName property and all DataSource-specific properties will be ignored. Default: none
#    spring.datasource.hikari.dataSource=

# This property sets the default schema for databases that support the concept of schemas.
# If this property is not specified, the default schema defined by the JDBC driver is used. Default: driver default
#    spring.datasource.hikari.schema=

# This property is only available via programmatic configuration or IoC container.
# This property allows you to set the instance of the java.util.concurrent.ThreadFactory that will be used for creating all threads used by the pool.
# It is needed in some restricted execution environments where threads can only be created through a ThreadFactory provided by the application container. Default: none
#    spring.datasource.hikari.threadFactory=

# This property is only available via programmatic configuration or IoC container.
# This property allows you to set the instance of the java.util.concurrent.ScheduledExecutorService that will be used for various internally scheduled tasks.
# If supplying HikariCP with a ScheduledThreadPoolExecutor instance, it is recommended that setRemoveOnCancelPolicy(true) is used. Default: none
#    spring.datasource.hikari.scheduledExecutor=
########################################################################################################################


# mybatis-plus
########################################################################################################################
# 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
# 如果是放在resource目录 classpath:/mapper/*Mapper.xml
mybatis-plus.mapper-locations=classpath:/mapper/*Mapper.xml
#实体扫描，多个package用逗号或者分号分隔
mybatis-plus.typeAliasesPackage=com.spring.boot.mybatis.dao.entity
#主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
mybatis-plus.global-config.id-type=0
#字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
mybatis-plus.global-config.field-strategy=2
#驼峰下划线转换
mybatis-plus.global-config.db-column-underline=true
#刷新mapper 调试神器
#mybatis-plus.global-config.refresh-mapper=true
#数据库大写下划线转换
#mybatis-plus.global-config.capital-mode=true
# Sequence序列接口实现类配置
# mybatis-plus.global-config.key-generator=com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
#逻辑删除配置（下面3个配置）
# mybatis-plus.global-config.logic-delete-value=1
# mybatis-plus.global-config.logic-not-delete-value=0
# mybatis-plus.global-config.sql-injector=com.baomidou.mybatisplus.mapper.LogicSqlInjector
#自定义填充策略接口实现
# mybatis-plus.global-config.meta-object-handler=com.baomidou.springboot.MyMetaObjectHandler
# mybatis-plus.configuration.map-underscore-to-camel-case=true
# mybatis-plus.configuration.cache-enabled=false
#配置JdbcTypeForNull
# mybatis-plus.configuration.jdbc-type-for-null='null'

















