# Application name
spring.application.name=spring-boot-redis

# EMBEDDED SERVER CONFIGURATION
# Server HTTP port.
server.port=8080

# LOGGING
logging.level.com.spring.boot.redis=DEBUG
logging.pattern.console=${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %4line %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

# REDIS (RedisProperties)
# Redis server host.
spring.redis.host=192.168.17.132
# Login password of the redis server.
# spring.redis.password=
# Redis server port.
spring.redis.port=6379
# Connection timeout.
spring.redis.timeout=3000

# #####################################################
# lettuce
# Maximum number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
spring.redis.lettuce.pool.max-active=8
# Maximum number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
spring.redis.lettuce.pool.max-idle=8
# Maximum amount of time a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
spring.redis.lettuce.pool.max-wait=-1ms
# Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
spring.redis.lettuce.pool.min-idle=0
# Shutdown timeout.
spring.redis.lettuce.shutdown-timeout=100ms

# #####################################################
# jedis
# Maximum number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
# spring.redis.jedis.pool.max-active=8
# Maximum number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
# spring.redis.jedis.pool.max-idle=8
# Maximum amount of time a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
# spring.redis.jedis.pool.max-wait=-1ms
# Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
# spring.redis.jedis.pool.min-idle=0