GET http://localhost:8080/resources
Accept: */*
Cache-Control: no-cache

########################################################################################################################
### Send POST request with json body
POST http://localhost:8080/security/auth/login
Content-Type: application/json

{
  "username": "rock",
  "password": "1234567890"
}

### Send POST request with json body
POST http://localhost:8080/security/auth/login
Content-Type: application/json

{
  "username": "jessica",
  "password": "1234567890"
}

########################################################################################################################
### GET request with a header
GET localhost:8080/security/auth/logout?username=rock
Accept: application/json

########################################################################################################################
### GET request with a header
GET localhost:8080/security/hello
Accept: application/json

########################################################################################################################
### Authorization by token, part 1. Retrieve and save token.
POST https://httpbin.org/post
Content-Type: application/json

{
  "token": "my-secret-token"
}

> {% client.global.set("auth_token", response.body.json.token); %}

### Authorization by token, part 2. Use token to authorize.
GET https://httpbin.org/headers
Authorization: Bearer {{auth_token}}

########################################################################################################################
