spring.application.name=spring-boot-tomcat
server.port=8070

# LOGGING
logging.level.com.spring.boot=DEBUG
logging.pattern.console=${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %4line %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

# tomcat
# Maximum queue length for incoming connection requests when all possible request processing threads are in use.
server.tomcat.accept-count=100
## Whether to buffer output such that it is flushed only periodically.
#server.tomcat.accesslog.buffered=true
# Whether to check for log file existence so it can be recreated it if an external process has renamed it.
server.tomcat.accesslog.check-exists=true
## Whether logging of the request will only be enabled if "ServletRequest.getAttribute(conditionIf)" does not yield null.
#server.tomcat.accesslog.condition-if=
## Whether logging of the request will only be enabled if "ServletRequest.getAttribute(conditionUnless)" yield null.
#server.tomcat.accesslog.condition-unless=
# Directory in which log files are created. Can be absolute or relative to the Tomcat base dir.
server.tomcat.accesslog.directory=/var/log/${spring.application.name}
# Enable access log.
server.tomcat.accesslog.enabled=true
## Character set used by the log file. Default to the system default character set.
#server.tomcat.accesslog.encoding=
# Date format to place in the log file name.
server.tomcat.accesslog.file-date-format=.yyyy-MM-dd
## Whether to use IPv6 canonical representation format as defined by RFC 5952.
#server.tomcat.accesslog.ipv6-canonical=false
## Locale used to format timestamps in log entries and in log file name suffix. Default to the default locale of the Java process.
#server.tomcat.accesslog.locale=
# Number of days to retain the access log files before they are removed.
server.tomcat.accesslog.max-days=-1
# Format pattern for access logs.
server.tomcat.accesslog.pattern=common
# Log file name prefix.
server.tomcat.accesslog.prefix=access_log
## Whether to defer inclusion of the date stamp in the file name until rotate time.
#server.tomcat.accesslog.rename-on-rotate=false
## Set request attributes for the IP address, Hostname, protocol, and port used for the request.
#server.tomcat.accesslog.request-attributes-enabled=false
# Whether to enable access log rotation.
server.tomcat.accesslog.rotate=true
# Log file name suffix.
server.tomcat.accesslog.suffix=.log
## Comma-separated list of additional patterns that match jars to ignore for TLD scanning. The special '?' and '*' characters can be used in the pattern to match one and only one character and zero or more characters respectively.
#server.tomcat.additional-tld-skip-patterns=
# Delay between the invocation of backgroundProcess methods. If a duration suffix is not specified, seconds will be used.
server.tomcat.background-processor-delay=10s
# Tomcat base directory. If not specified, a temporary directory is used.
server.tomcat.basedir=/
## Amount of time the connector will wait, after accepting a connection, for the request URI line to be presented.
#server.tomcat.connection-timeout=
## Name of the HTTP header from which the remote host is extracted.
#server.tomcat.host-header=X-Forwarded-Host
## Regular expression that matches proxies that are to be trusted.
#server.tomcat.internal-proxies=10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|192\\.168\\.\\d{1,3}\\.\\d{1,3}|169\\.254\\.\\d{1,3}\\.\\d{1,3}|127\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|172\\.1[6-9]{1}\\.\\d{1,3}\\.\\d{1,3}|172\\.2[0-9]{1}\\.\\d{1,3}\\.\\d{1,3}|172\\.3[0-1]{1}\\.\\d{1,3}\\.\\d{1,3}|0:0:0:0:0:0:0:1|::1
# Maximum number of connections that the server accepts and processes at any given time. Once the limit has been reached, the operating system may still accept connections based on the "acceptCount" property.
server.tomcat.max-connections=8192
# Maximum size of the form content in any HTTP post request.
server.tomcat.max-http-form-post-size=2MB
# Maximum amount of request body to swallow.
server.tomcat.max-swallow-size=2MB
# Maximum amount of worker threads.
server.tomcat.max-threads=200
# Whether Tomcat's MBean Registry should be enabled.
server.tomcat.mbeanregistry.enabled=false
# Minimum amount of worker threads.
server.tomcat.min-spare-threads=10
## Name of the HTTP header used to override the original port value.
#server.tomcat.port-header=X-Forwarded-Port
# Maximum number of idle processors that will be retained in the cache and reused with a subsequent request. When set to -1 the cache will be unlimited with a theoretical maximum size equal to the maximum number of connections.
server.tomcat.processor-cache=200
## Header that holds the incoming protocol, usually named "X-Forwarded-Proto".
#server.tomcat.protocol-header=
## Value of the protocol header indicating whether the incoming request uses SSL.
#server.tomcat.protocol-header-https-value=https
# Whether requests to the context root should be redirected by appending a / to the path.
server.tomcat.redirect-context-root=true
## Comma-separated list of additional unencoded characters that should be allowed in URI paths. Only "< > [ \ ] ^ ` { | }" are allowed.
#server.tomcat.relaxed-path-chars=
## Comma-separated list of additional unencoded characters that should be allowed in URI query strings. Only "< > [ \ ] ^ ` { | }" are allowed.
#server.tomcat.relaxed-query-chars=
## Name of the HTTP header from which the remote IP is extracted. For instance, `X-FORWARDED-FOR`.
#server.tomcat.remote-ip-header=
# Whether static resource caching is permitted for this web application.
server.tomcat.resource.allow-caching=true
## Time-to-live of the static resource cache.
#server.tomcat.resource.cache-ttl=
# Character encoding to use to decode the URI.
server.tomcat.uri-encoding=UTF-8
## Whether HTTP 1.1 and later location headers generated by a call to sendRedirect will use relative or absolute redirects.
#server.tomcat.use-relative-redirects=false
