nacos.discovery.server-addr=localhost:8848

server.port=8080
spring.application.name=spring-boot-nacos-discovery

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# http://127.0.0.1:8080/actuator/nacos-discovery
# http://localhost:8080/actuator/health
