
#spring.data.neo4j.uri=bolt://localhost:7687
#spring.data.neo4j.username=neo4j
#spring.data.neo4j.password=neo4j

spring.data.neo4j.uri=bolt://192.168.81.129:7687

## disable the embedded mode
spring.data.neo4j.embedded.enabled=false
## enable persistence for the embedded mode by providing a path to a database file
## Exception: java.lang.IllegalArgumentException: URI has an authority component
#spring.data.neo4j.uri=file://var/tmp/neo4j.db
## Using Native Types
#spring.data.neo4j.use-native-types=true
## close the "Open Session in View" pattern
#spring.data.neo4j.open-in-view=true
