CREATE TABLE COMPANY
(
    ID        INT PRIMARY KEY NOT NULL,
    TENANT_ID VARCHAR(20)     NOT NULL,
    NAME      TEXT            NOT NULL,
    AGE       INT             NOT NULL,
    ADDRESS   CHAR(50),
    SALARY    REAL
);