# Application name
spring.application.name=spring-boot-mybatisplus-druid


# EMBEDDED SERVER CONFIGURATION
# Server HTTP port.
server.port=8080


# LOGGING
########################################################################################################################
logging.level.root=WARN
logging.level.org.springframework.web=DEBUG
logging.level.com.spring.boot.mybatis=DEBUG
logging.pattern.console=${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %4line %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}
########################################################################################################################


# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
########################################################################################################################
# Druid will use the above plus the following to setup connection pooling
# Fully qualified name of the JDBC driver. Auto-detected based on the URL by default.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JDBC URL of the database.
# useSSL=false 关闭SSL验证
# serverTimezone=UTC 设置时区
spring.datasource.url=jdbc:mysql://localhost:3306/artanis?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=utf8
# Login username of the database.
spring.datasource.username=root
# Login password of the database.
spring.datasource.password=.Gaohang,321

# Druid specific settings
########################################################################################################################
# Fully qualified name of the connection pool implementation to use. By default, it is auto-detected from the classpath.
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
# 连接池配置
# 初始化大小，最小，最大
spring.datasource.druid.initial-size=5
spring.datasource.druid.max-active=20
spring.datasource.druid.min-idle=5
# 配置获取连接等待超时的时间
spring.datasource.druid.max-wait=60000
# 打开PSCache，并且指定每个连接上PSCache的大小
spring.datasource.druid.pool-prepared-statements=true
spring.datasource.druid.max-pool-prepared-statement-per-connection-size=20
# 和上面的等价
spring.datasource.druid.max-open-prepared-statements=20
spring.datasource.druid.validation-query=SELECT 1 FROM DUAL
spring.datasource.druid.validation-query-timeout=300000
spring.datasource.druid.test-on-borrow=false
spring.datasource.druid.test-on-return=false
spring.datasource.druid.test-while-idle=true
# 配置间隔多久进行一次检测，检测需要关闭的空闲连接，单位是毫秒
spring.datasource.druid.time-between-eviction-runs-millis=60000
# 配置一个连接在池中最小、最大生存时间，单位是毫秒
spring.datasource.druid.min-evictable-idle-time-millis=300000
spring.datasource.druid.max-evictable-idle-time-millis=600000


# mybatis-plus
########################################################################################################################
# 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
# 如果是放在resource目录 classpath:/mapper/*Mapper.xml
mybatis-plus.mapper-locations=classpath:/mapper/*Mapper.xml
#实体扫描，多个package用逗号或者分号分隔
mybatis-plus.typeAliasesPackage=com.spring.boot.mybatis.dao.entity
#主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
mybatis-plus.global-config.id-type=0
#字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
mybatis-plus.global-config.field-strategy=2
#驼峰下划线转换
mybatis-plus.global-config.db-column-underline=true
#刷新mapper 调试神器
#mybatis-plus.global-config.refresh-mapper=true
#数据库大写下划线转换
#mybatis-plus.global-config.capital-mode=true
# Sequence序列接口实现类配置
# mybatis-plus.global-config.key-generator=com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
#逻辑删除配置（下面3个配置）
# mybatis-plus.global-config.logic-delete-value=1
# mybatis-plus.global-config.logic-not-delete-value=0
# mybatis-plus.global-config.sql-injector=com.baomidou.mybatisplus.mapper.LogicSqlInjector
#自定义填充策略接口实现
# mybatis-plus.global-config.meta-object-handler=com.baomidou.springboot.MyMetaObjectHandler
# mybatis-plus.configuration.map-underscore-to-camel-case=true
# mybatis-plus.configuration.cache-enabled=false
#配置JdbcTypeForNull
# mybatis-plus.configuration.jdbc-type-for-null='null'

















